import type { VectorClock } from "../contracts/envelopes.ts";
import { OnyxError } from "../contracts/errors.ts";
import { assertEmittedEvent } from "../contracts/validation.ts";
import { sha256 } from "../shared/canonical-json.ts";
import { utcInstant, uuidV7 } from "../shared/identifiers.ts";
import { toOrganizationView, type OrganizationRepository } from "./repository.ts";
import type { OrganizationCommand, OrganizationEvent, OrganizationStructure, OrganizationView } from "./types.ts";
import { validateOrganizationCommand } from "./validation.ts";
export class OrganizationService {
  readonly repository: OrganizationRepository; readonly #now: () => Date; readonly #replicaId: string;
  constructor(repository: OrganizationRepository, options: {now?: () => Date; replicaId?: string} = {}) { this.repository = repository; this.#now = options.now ?? (() => new Date()); this.#replicaId = options.replicaId ?? "organization-service"; }
  async execute(input: unknown): Promise<OrganizationEvent> { validateOrganizationCommand(input); const command = input; const replay = await this.#replay(command); if (replay) return replay; if (command.command_type === "CreateOrganization") return this.#create(command); const state = await this.#load(command); let eventType: OrganizationEvent["event_type"], payload: unknown;
    switch (command.command_type) {
      case "CreateWorkspace": this.#authorize(command, "organization:workspace:create"); if (state.workspaces[command.payload.workspace_id]) throw new OnyxError("VERSION_CONFLICT", "workspace exists"); state.workspaces[command.payload.workspace_id] = {workspaceId: command.payload.workspace_id, name: command.payload.name}; eventType = "WorkspaceCreated"; payload = structuredClone(command.payload); break;
      case "CreateDepartment": this.#authorize(command, "organization:department:create"); if (state.departments[command.payload.department_id]) throw new OnyxError("VERSION_CONFLICT", "department exists"); if (command.payload.parent_department_id && !state.departments[command.payload.parent_department_id]) throw new OnyxError("NOT_FOUND", "parent department not found"); state.departments[command.payload.department_id] = {departmentId: command.payload.department_id, name: command.payload.name, ...(command.payload.parent_department_id ? {parentDepartmentId: command.payload.parent_department_id} : {}), status: "ACTIVE"}; eventType = "DepartmentCreated"; payload = structuredClone(command.payload); break;
      case "CreateTeam": this.#authorize(command, "organization:team:create"); if (state.teams[command.payload.team_id]) throw new OnyxError("VERSION_CONFLICT", "team exists"); this.#activeDepartment(state, command.payload.department_id); state.teams[command.payload.team_id] = {teamId: command.payload.team_id, departmentId: command.payload.department_id, name: command.payload.name}; eventType = "TeamCreated"; payload = structuredClone(command.payload); break;
      case "CreateGroup": this.#authorize(command, "organization:group:create"); if (state.groups[command.payload.group_id]) throw new OnyxError("VERSION_CONFLICT", "group exists"); state.groups[command.payload.group_id] = {groupId: command.payload.group_id, name: command.payload.name}; eventType = "GroupCreated"; payload = structuredClone(command.payload); break;
      case "MoveTeam": this.#authorize(command, "organization:team:move"); { const team = state.teams[command.payload.team_id]; if (!team) throw new OnyxError("NOT_FOUND", "team not found"); this.#activeDepartment(state, command.payload.to_department_id); team.departmentId = command.payload.to_department_id; eventType = "TeamMoved"; payload = {team_id: team.teamId, department_id: team.departmentId}; } break;
      case "ArchiveDepartment": this.#authorize(command, "organization:department:archive"); { const department = this.#activeDepartment(state, command.payload.department_id); if (Object.values(state.teams).some((team) => team.departmentId === department.departmentId)) throw new OnyxError("INVALID_STATE_TRANSITION", "move teams before archiving department"); department.status = "ARCHIVED"; eventType = "DepartmentArchived"; payload = {department_id: department.departmentId, new_status: "ARCHIVED"}; } break;
      case "ArchiveOrganization": this.#authorize(command, "organization:archive"); state.status = "ARCHIVED"; state.lifecycleEpoch += 1; eventType = "OrganizationArchived"; payload = {new_status: "ARCHIVED"}; break;
    }
    state.version += 1; return this.#publish(command, state, eventType, payload, false);
  }
  async #create(command: Extract<OrganizationCommand, {command_type: "CreateOrganization"}>) { this.#authorize(command, "organization:create"); if (await this.repository.find(command.payload.organization_id)) throw new OnyxError("VERSION_CONFLICT", "organization exists"); if (command.expected_version !== undefined && command.expected_version !== 0) throw new OnyxError("VERSION_CONFLICT", "new organization must expect version 0"); const state: OrganizationStructure = {organizationId: command.payload.organization_id, name: command.payload.name, slug: command.payload.slug, status: "ACTIVE", version: 1, lifecycleEpoch: 0, authorityEpoch: command.authority_proof.authority_epoch, workspaces: {}, departments: {}, teams: {}, groups: {}}; return this.#publish(command, state, "OrganizationCreated", structuredClone(command.payload), true); }
  async #load(command: Exclude<OrganizationCommand, {command_type: "CreateOrganization"}>) { const state = await this.repository.find(command.payload.organization_id); if (!state) throw new OnyxError("NOT_FOUND", "organization not found"); if (state.status === "ARCHIVED") throw new OnyxError("INVALID_STATE_TRANSITION", "organization is archived"); if (command.expected_version !== undefined && command.expected_version !== state.version) throw new OnyxError("VERSION_CONFLICT", "expected_version does not match"); if (command.expected_lifecycle_epoch !== undefined && command.expected_lifecycle_epoch !== state.lifecycleEpoch) throw new OnyxError("LIFECYCLE_EPOCH_MISMATCH", "expected_lifecycle_epoch does not match"); if (command.expected_authority_epoch !== undefined && command.expected_authority_epoch !== state.authorityEpoch) throw new OnyxError("AUTHORITY_EPOCH_MISMATCH", "expected_authority_epoch does not match"); return state; }
  #activeDepartment(state: OrganizationStructure, id: string) { const value = state.departments[id]; if (!value || value.status !== "ACTIVE") throw new OnyxError("NOT_FOUND", "active department not found"); return value; }
  #authorize(command: OrganizationCommand, scope: string) { if (!command.authority_proof.scope.includes(scope) || Date.parse(command.authority_proof.expires_at) <= this.#now().getTime()) throw new OnyxError("AUTHORITY_PROOF_INVALID", `${scope} authority is missing or expired`); }
  async #replay(command: OrganizationCommand) { const prior = await this.repository.findOperation(command.operation_id); if (!prior) return undefined; if (prior.fingerprint !== sha256(command)) throw new OnyxError("IDEMPOTENCY_KEY_REUSE", "operation_id reused"); return prior.event; }
  async #publish(command: OrganizationCommand, state: OrganizationStructure, eventType: OrganizationEvent["event_type"], payload: unknown, create: boolean) { const now = this.#now(), occurredAt = utcInstant(now); const unsigned = {event_id: uuidV7(now), event_type: eventType, schema_version: 1 as const, organization_id: state.organizationId, aggregate: {aggregate_type: "Organization", object_id: state.organizationId}, aggregate_version: state.version, lifecycle_epoch: state.lifecycleEpoch, authority_epoch: state.authorityEpoch, operation_id: command.operation_id, actor_context: command.actor_context, occurred_at: occurredAt, recorded_at: occurredAt, vector_clock: this.#advance(command.vector_clock), correlation_id: command.correlation_id, causation_id: command.command_id, payload}; const event = {...unsigned, audit: {provenance: `${command.command_type}@1`, integrity_digest: sha256(unsigned)}} as OrganizationEvent; assertEmittedEvent(event, eventType, "Organization"); await this.repository.commit(state, event, command.operation_id, {fingerprint: sha256(command), event}, create); return structuredClone(event); }
  #advance(clock: VectorClock): VectorClock { return {...clock, [this.#replicaId]: (clock[this.#replicaId] ?? 0) + 1}; }
  async getOrganization(id: string): Promise<OrganizationView> { const state = await this.repository.find(id); if (!state) throw new OnyxError("NOT_FOUND", "organization not found"); return toOrganizationView(state); }
  async listOrganizations(organizationId: string, afterId?: string, limit = 100) { return (await this.repository.list(organizationId, afterId, limit)).map(toOrganizationView); }
  async getHistory(id: string, afterVersion = 0, limit = 100) { if (!Number.isInteger(afterVersion) || afterVersion < 0 || !Number.isInteger(limit) || limit < 1 || limit > 1000) throw new OnyxError("INVALID_ARGUMENT", "invalid history pagination"); await this.getOrganization(id); return this.repository.history(id, afterVersion, limit); }
}
