import type {CommandEnvelope,EventEnvelope,UuidV7} from "../contracts/envelopes.ts";
export interface CreateMeetingPayload{meeting_id:UuidV7;title:string;organizer_id:UuidV7;scheduled_start_at:string;timezone:string}
export interface InviteParticipantPayload{meeting_id:UuidV7;participant_id:UuidV7;role:string}
export interface RemoveParticipantPayload{meeting_id:UuidV7;participant_id:UuidV7;reason:string}
export interface StartMeetingPayload{meeting_id:UuidV7;started_at:string}
export interface RecordDecisionPayload{meeting_id:UuidV7;decision_id:UuidV7;title:string;decision:string;decided_by_id:UuidV7}
export interface ProposeActionItemPayload{meeting_id:UuidV7;action_item_id:UuidV7;title:string;assignee_id:UuidV7;due_at?:string}
export interface EndMeetingPayload{meeting_id:UuidV7;ended_at:string;summary:string}
export interface CancelMeetingPayload{meeting_id:UuidV7;reason:string}
export type MeetingCommand=CommandEnvelope<"CreateMeeting",CreateMeetingPayload>|CommandEnvelope<"InviteParticipant",InviteParticipantPayload>|CommandEnvelope<"RemoveParticipant",RemoveParticipantPayload>|CommandEnvelope<"StartMeeting",StartMeetingPayload>|CommandEnvelope<"RecordDecision",RecordDecisionPayload>|CommandEnvelope<"ProposeActionItem",ProposeActionItemPayload>|CommandEnvelope<"EndMeeting",EndMeetingPayload>|CommandEnvelope<"CancelMeeting",CancelMeetingPayload>;
export type MeetingEvent=EventEnvelope<"MeetingCreated",CreateMeetingPayload>|EventEnvelope<"ParticipantInvited",InviteParticipantPayload>|EventEnvelope<"ParticipantRemoved",RemoveParticipantPayload>|EventEnvelope<"MeetingStarted",StartMeetingPayload>|EventEnvelope<"DecisionRecorded",RecordDecisionPayload>|EventEnvelope<"ActionItemProposed",ProposeActionItemPayload>|EventEnvelope<"MeetingEnded",EndMeetingPayload>|EventEnvelope<"MeetingCancelled",CancelMeetingPayload>;
export interface Meeting{meetingId:UuidV7;organizationId:UuidV7;title:string;organizerId:UuidV7;scheduledStartAt:string;timezone:string;status:"SCHEDULED"|"IN_PROGRESS"|"ENDED"|"CANCELLED";startedAt?:string;endedAt?:string;summary?:string;version:number;lifecycleEpoch:number;authorityEpoch:number;participants:Record<UuidV7,{participantId:UuidV7;role:string}>;decisions:Record<UuidV7,{decisionId:UuidV7;title:string;decision:string;decidedById:UuidV7}>;actionItems:Record<UuidV7,{actionItemId:UuidV7;title:string;assigneeId:UuidV7;dueAt?:string}>}
export interface MeetingView{meeting_id:UuidV7;organization_id:UuidV7;title:string;organizer_id:UuidV7;scheduled_start_at:string;timezone:string;status:Meeting["status"];started_at?:string;ended_at?:string;summary?:string;version:number;lifecycle_epoch:number;authority_epoch:number;participants:Record<string,{participant_id:UuidV7;role:string}>;decisions:Record<string,{decision_id:UuidV7;title:string;decision:string;decided_by_id:UuidV7}>;action_items:Record<string,{action_item_id:UuidV7;title:string;assignee_id:UuidV7;due_at?:string}>}
