import assert from "node:assert/strict";
import {describe,it} from "node:test";
import {OnyxError} from "../src/contracts/errors.ts";
import {InMemoryContextLinkRepository} from "../src/context-link/repository.ts";
import {ContextLinkService} from "../src/context-link/service.ts";
import {contextLinkCommand,testId} from "./fixtures.ts";
const now=()=>new Date("2026-07-29T20:00:01.000Z"),id=testId(850),source={aggregate_type:"Mission",object_id:testId(14)},target={aggregate_type:"Task",object_id:testId(400)};
describe("ContextLinkService",()=>{
  it("creates, updates, archives, and restores a validated cross-context link",async()=>{const known=new Set([`${source.aggregate_type}:${source.object_id}`,`${target.aggregate_type}:${target.object_id}`]);const service=new ContextLinkService({repository:new InMemoryContextLinkRepository(),now,requireObject:async(_organizationId,reference)=>{if(!known.has(`${reference.aggregate_type}:${reference.object_id}`))throw new OnyxError("NOT_FOUND","object not found");}});const commands=[
    contextLinkCommand("CreateContextLink",1,{context_link_id:id,source_ref:source,target_ref:target,relation_type:"DELIVERS",strength:"STRONG",metadata:{origin:"planning"}},"context:create",0),
    contextLinkCommand("UpdateContextMetadata",2,{context_link_id:id,metadata:{origin:"execution",owner:"operations"}},"context:metadata:update",1),
    contextLinkCommand("ChangeContextStrength",3,{context_link_id:id,strength:"CRITICAL",reason:"Critical path"},"context:strength:change",2),
    contextLinkCommand("ArchiveContextLink",4,{context_link_id:id,reason:"Temporarily inactive"},"context:archive",3),
    contextLinkCommand("RestoreContextLink",5,{context_link_id:id,reason:"Dependency active again"},"context:restore",4,1),
  ];const events=[];for(const command of commands)events.push(await service.execute(command));assert.deepEqual(events.map((event)=>event.event_type),["ContextLinkCreated","ContextMetadataUpdated","ContextStrengthChanged","ContextLinkArchived","ContextLinkRestored"]);const view=await service.getContextLink(testId(13),id);assert.equal(view.status,"ACTIVE");assert.equal(view.strength,"CRITICAL");assert.equal(view.version,5);assert.equal(view.lifecycle_epoch,2);assert.deepEqual(view.metadata,{origin:"execution",owner:"operations"});});
  it("requires both endpoints and rejects changed replay and invalid transitions",async()=>{const missing=new ContextLinkService({repository:new InMemoryContextLinkRepository(),now,requireObject:async(_organizationId,reference)=>{if(reference.object_id!==source.object_id)throw new OnyxError("NOT_FOUND","object not found");}}),create=contextLinkCommand("CreateContextLink",20,{context_link_id:id,source_ref:source,target_ref:target,relation_type:"DELIVERS",strength:"NORMAL",metadata:{}},"context:create",0);await assert.rejects(missing.execute(create),(error:unknown)=>error instanceof OnyxError&&error.code==="NOT_FOUND");const service=new ContextLinkService({repository:new InMemoryContextLinkRepository(),now,requireObject:async()=>undefined}),created=await service.execute(create);assert.deepEqual(await service.execute(create),created);await assert.rejects(service.execute({...create,payload:{...create.payload,relation_type:"BLOCKS"}}),(error:unknown)=>error instanceof OnyxError&&error.code==="IDEMPOTENCY_KEY_REUSE");await service.execute(contextLinkCommand("ArchiveContextLink",21,{context_link_id:id,reason:"Done"},"context:archive",1));await assert.rejects(service.execute(contextLinkCommand("ArchiveContextLink",22,{context_link_id:id,reason:"Again"},"context:archive",2,1)),(error:unknown)=>error instanceof OnyxError&&error.code==="INVALID_STATE_TRANSITION");});
});
