use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
pub type UuidV7 = String;
pub type UtcInstant = String;
pub type VectorClock = BTreeMap<String, u64>;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DomainObjectRef {
    pub aggregate_type: String,
    pub object_id: UuidV7,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ActorType {
    User,
    Service,
    Device,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActorContext {
    pub principal_id: UuidV7,
    pub actor_type: ActorType,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device_id: Option<UuidV7>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub membership_id: Option<UuidV7>,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuthorityProof {
    pub proof_ref: String,
    pub scope: Vec<String>,
    pub expires_at: UtcInstant,
    pub authority_epoch: u64,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum CommandType {
    CreateMission,
    CreateBlueprintRevision,
    SubmitBlueprint,
    ActivateMission,
    PauseMission,
    OperationalHaltMission,
    ResumeMission,
    RestartMission,
    CloseMission,
    ArchiveMission,
    CancelMission,
    CreateTask,
    AssignOwner,
    ChangePriority,
    AddDependency,
    StartTask,
    PauseTask,
    BlockTask,
    SubmitCompletion,
    ApproveTask,
    ReopenTask,
    CloseTask,
    CancelTask,
    CreateOrganization,
    CreateWorkspace,
    CreateDepartment,
    CreateTeam,
    CreateGroup,
    MoveTeam,
    ArchiveDepartment,
    ArchiveOrganization,
    CreateUser,
    AssignRole,
    RevokeRole,
    RegisterDevice,
    RevokeDevice,
    DelegateAuthority,
    RevokeDelegation,
    DisableUser,
    EnableUser,
    CreateContextLink,
    UpdateContextMetadata,
    ChangeContextStrength,
    ArchiveContextLink,
    RestoreContextLink,
    CreateMeeting,
    InviteParticipant,
    RemoveParticipant,
    StartMeeting,
    RecordDecision,
    ProposeActionItem,
    EndMeeting,
    CancelMeeting,
    CreateConversation,
    AddMember,
    PostMessage,
    EditMessage,
    RedactMessage,
    AddReaction,
    RemoveReaction,
    ArchiveConversation,
    CreateFileAsset,
    StartUpload,
    AppendChunk,
    FinalizeUpload,
    CreateVersion,
    GrantFileAccess,
    RevokeFileAccess,
    QuarantineFile,
    ArchiveFile,
    CreateReport,
    AddEvidence,
    SubmitReport,
    VerifyEvidence,
    RejectEvidence,
    ApproveReport,
    RejectReport,
    ArchiveReport,
    CreateApproval,
    AssignApprover,
    Approve,
    Reject,
    RequestChanges,
    DelegateApproval,
    EscalateApproval,
    CancelApproval,
    ReverseApproval,
    ReopenApproval,
    CreateTimeline,
    AddMilestone,
    SetDeadline,
    MoveDeadline,
    DefineCriticalMarker,
    ActivatePenaltyZone,
    ResolveScheduleException,
    ArchiveTimeline,
    CreateCapacityProfile,
    UpdateAvailability,
    AllocateWorkload,
    CaptureCapacitySnapshot,
    RecalculateCapacity,
    ArchiveCapacityProfile,
    GenerateForecast,
    CreateScenario,
    RecalculateForecast,
    PublishForecast,
    ArchiveForecast,
    CreateAutomationRule,
    EnableRule,
    DisableRule,
    EvaluateRule,
    ExecuteAction,
    RetryExecution,
    CompensateExecution,
    ArchiveRule,
    CreateNotification,
    ResolveRecipients,
    SendNotification,
    RetryDelivery,
    EscalateNotification,
    AcknowledgeNotification,
    ArchiveNotification,
    StartSynchronization,
    OfferOperationBatch,
    AcceptOperationBatch,
    MergeOperationBatch,
    ResolveConflict,
    EscalateConflict,
    AcknowledgeSynchronization,
    CloseSynchronization,
    AppendAuditEntry,
    SealAuditPartition,
    CreateAuditExport,
    VerifyIntegrity,
    ArchiveAuditPartition,
    CreatePolicy,
    CreatePolicyVersion,
    PublishPolicyVersion,
    EvaluatePolicy,
    RegisterViolation,
    ApplyLegalHold,
    ReleaseLegalHold,
    RetirePolicy,
    DefineRateLimitPolicy,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum EventType {
    MissionCreated,
    MissionBlueprintRevisionCreated,
    MissionBlueprintSubmitted,
    MissionActivated,
    MissionPaused,
    MissionOperationallyHalted,
    MissionResumed,
    MissionRestarted,
    MissionClosed,
    MissionArchived,
    MissionCancelled,
    TaskCreated,
    TaskOwnerAssigned,
    TaskPriorityChanged,
    TaskDependencyAdded,
    TaskStarted,
    TaskPaused,
    TaskBlocked,
    TaskCompletionSubmitted,
    TaskApproved,
    TaskReopened,
    TaskClosed,
    TaskCancelled,
    OrganizationCreated,
    WorkspaceCreated,
    DepartmentCreated,
    TeamCreated,
    GroupCreated,
    TeamMoved,
    DepartmentArchived,
    OrganizationArchived,
    UserCreated,
    RoleAssigned,
    RoleRevoked,
    DeviceRegistered,
    DeviceRevoked,
    AuthorityDelegated,
    DelegationRevoked,
    UserDisabled,
    UserEnabled,
    ContextLinkCreated,
    ContextMetadataUpdated,
    ContextStrengthChanged,
    ContextLinkArchived,
    ContextLinkRestored,
    MeetingCreated,
    ParticipantInvited,
    ParticipantRemoved,
    MeetingStarted,
    DecisionRecorded,
    ActionItemProposed,
    MeetingEnded,
    MeetingCancelled,
    ConversationCreated,
    ConversationMemberAdded,
    MessagePosted,
    MessageEdited,
    MessageRedacted,
    ReactionAdded,
    ReactionRemoved,
    ConversationArchived,
    FileAssetCreated,
    UploadStarted,
    ChunkAccepted,
    UploadFinalized,
    FileVersionCreated,
    FileAccessGranted,
    FileAccessRevoked,
    FileQuarantined,
    FileArchived,
    ReportCreated,
    EvidenceAdded,
    ReportSubmitted,
    EvidenceVerified,
    EvidenceRejected,
    ReportApproved,
    ReportRejected,
    ReportArchived,
    ApprovalCreated,
    ApproverAssigned,
    ApprovalGranted,
    ApprovalRejected,
    ChangesRequested,
    ApprovalDelegated,
    ApprovalEscalated,
    ApprovalCancelled,
    ApprovalReversed,
    ApprovalReopened,
    TimelineCreated,
    MilestoneAdded,
    DeadlineChanged,
    DeadlineMoved,
    CriticalMarkerDefined,
    CriticalMarkerReached,
    DeadlineReached,
    PenaltyZoneActivated,
    ScheduleExceptionRaised,
    TimelineArchived,
    CapacityProfileCreated,
    AvailabilityUpdated,
    WorkloadAllocated,
    CapacitySnapshotCaptured,
    CapacityRecalculated,
    CapacityProfileArchived,
    ForecastGenerated,
    ScenarioCreated,
    ForecastRecalculated,
    ForecastPublished,
    ForecastArchived,
    AutomationRuleCreated,
    AutomationRuleEnabled,
    AutomationRuleDisabled,
    AutomationRuleTriggered,
    AutomationActionExecuted,
    AutomationExecutionFailed,
    AutomationExecutionCompensated,
    AutomationRuleArchived,
    NotificationCreated,
    RecipientsResolved,
    NotificationSent,
    NotificationDeliveryFailed,
    NotificationEscalated,
    NotificationAcknowledged,
    NotificationArchived,
    SynchronizationStarted,
    OperationBatchOffered,
    OperationBatchAccepted,
    OperationBatchMerged,
    ConflictDetected,
    ConflictResolved,
    ConflictEscalated,
    SynchronizationAcknowledged,
    SynchronizationClosed,
    AuditEntryAppended,
    AuditPartitionSealed,
    AuditExportCreated,
    AuditIntegrityVerified,
    AuditPartitionArchived,
    PolicyCreated,
    PolicyVersionCreated,
    PolicyVersionPublished,
    PolicyEvaluated,
    PolicyViolationDetected,
    LegalHoldApplied,
    LegalHoldReleased,
    PolicyRetired,
    RateLimitPolicyDefined,
    QuotaThresholdReached,
    QuotaExceeded,
    RateLimitTriggered,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommandEnvelope<P> {
    pub command_id: UuidV7,
    pub operation_id: UuidV7,
    pub command_type: CommandType,
    pub schema_version: u16,
    pub organization_id: UuidV7,
    pub target: DomainObjectRef,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expected_version: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expected_lifecycle_epoch: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expected_authority_epoch: Option<u64>,
    pub actor_context: ActorContext,
    pub authority_proof: AuthorityProof,
    pub issued_at: UtcInstant,
    pub vector_clock: VectorClock,
    pub correlation_id: UuidV7,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub causation_id: Option<UuidV7>,
    pub payload: P,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditContext {
    pub provenance: String,
    pub integrity_digest: String,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventEnvelope<P> {
    pub event_id: UuidV7,
    pub event_type: EventType,
    pub schema_version: u16,
    pub organization_id: UuidV7,
    pub aggregate: DomainObjectRef,
    pub aggregate_version: u64,
    pub lifecycle_epoch: u64,
    pub authority_epoch: u64,
    pub operation_id: UuidV7,
    pub actor_context: ActorContext,
    pub occurred_at: UtcInstant,
    pub recorded_at: UtcInstant,
    pub vector_clock: VectorClock,
    pub correlation_id: UuidV7,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub causation_id: Option<UuidV7>,
    pub audit: AuditContext,
    pub payload: P,
}

#[cfg(test)]
mod tests {
    use super::{ActorContext, ActorType, CommandType, EventType};

    #[test]
    fn command_and_event_names_serialize_to_contract_names() {
        assert_eq!(
            serde_json::to_string(&CommandType::CreateMission).unwrap(),
            "\"CreateMission\""
        );
        assert_eq!(
            serde_json::to_string(&EventType::MissionCreated).unwrap(),
            "\"MissionCreated\""
        );
    }

    #[test]
    fn actor_context_uses_contract_values_and_omits_absent_optional_fields() {
        let actor = ActorContext {
            principal_id: "01900000-0000-7000-8000-000000000001".into(),
            actor_type: ActorType::Service,
            device_id: None,
            membership_id: None,
        };
        let value = serde_json::to_value(actor).unwrap();
        assert_eq!(value["actor_type"], "SERVICE");
        assert!(value.get("device_id").is_none());
        assert!(value.get("membership_id").is_none());
    }
}
