import type { VectorClock } from "../contracts/envelopes.ts";
import { OnyxError } from "../contracts/errors.ts";
import { assertEmittedEvent } from "../contracts/validation.ts";
import { sha256 } from "../shared/canonical-json.ts";
import { utcInstant, uuidV7 } from "../shared/identifiers.ts";
import { toUserIdentityView, type IdentityRepository } from "./repository.ts";
import type { IdentityCommand, IdentityEvent, UserIdentity, UserIdentityView } from "./types.ts";
import { validateIdentityCommand } from "./validation.ts";

const scopes: Record<IdentityCommand["command_type"], string> = {CreateUser: "identity-authority:user:create", AssignRole: "identity-authority:role:assign", RevokeRole: "identity-authority:role:revoke", RegisterDevice: "identity-authority:device:register", RevokeDevice: "identity-authority:device:revoke", DelegateAuthority: "identity-authority:delegate", RevokeDelegation: "identity-authority:delegation:revoke", DisableUser: "identity-authority:user:disable", EnableUser: "identity-authority:user:enable"};
export class IdentityService {
  readonly repository: IdentityRepository; readonly #now: () => Date; readonly #replicaId: string;
  constructor(repository: IdentityRepository, options: {now?: () => Date; replicaId?: string} = {}) { this.repository = repository; this.#now = options.now ?? (() => new Date()); this.#replicaId = options.replicaId ?? "identity-authority-service"; }
  async execute(input: unknown): Promise<IdentityEvent> { validateIdentityCommand(input); const command = input; this.#authorize(command); const replay = await this.#replay(command); if (replay) return replay; if (command.command_type === "CreateUser") return this.#create(command); const state = await this.#load(command); let eventType: IdentityEvent["event_type"];
    switch (command.command_type) {
      case "AssignRole": if (state.roles[command.payload.role_id]) throw new OnyxError("VERSION_CONFLICT", "role already assigned"); state.roles[command.payload.role_id] = {roleId: command.payload.role_id, assignedAt: utcInstant(this.#now())}; eventType = "RoleAssigned"; break;
      case "RevokeRole": if (!state.roles[command.payload.role_id]) throw new OnyxError("NOT_FOUND", "role assignment not found"); delete state.roles[command.payload.role_id]; state.authorityEpoch += 1; eventType = "RoleRevoked"; break;
      case "RegisterDevice": if (state.devices[command.payload.device_id]) throw new OnyxError("VERSION_CONFLICT", "device exists"); state.devices[command.payload.device_id] = {deviceId: command.payload.device_id, name: command.payload.name, publicKeyThumbprint: command.payload.public_key_thumbprint, status: "ACTIVE"}; eventType = "DeviceRegistered"; break;
      case "RevokeDevice": { const device = state.devices[command.payload.device_id]; if (!device || device.status !== "ACTIVE") throw new OnyxError("NOT_FOUND", "active device not found"); device.status = "REVOKED"; state.authorityEpoch += 1; eventType = "DeviceRevoked"; } break;
      case "DelegateAuthority": if (command.payload.delegatee_id === state.userId) throw new OnyxError("INVALID_ARGUMENT", "self delegation is not allowed"); if (Date.parse(command.payload.expires_at) <= this.#now().getTime()) throw new OnyxError("INVALID_ARGUMENT", "delegation expiry must be in the future"); if (state.delegations[command.payload.delegation_id]) throw new OnyxError("VERSION_CONFLICT", "delegation exists"); state.delegations[command.payload.delegation_id] = {delegationId: command.payload.delegation_id, delegateeId: command.payload.delegatee_id, scopes: [...command.payload.scopes], expiresAt: command.payload.expires_at, status: "ACTIVE"}; eventType = "AuthorityDelegated"; break;
      case "RevokeDelegation": { const delegation = state.delegations[command.payload.delegation_id]; if (!delegation || delegation.status !== "ACTIVE") throw new OnyxError("NOT_FOUND", "active delegation not found"); delegation.status = "REVOKED"; state.authorityEpoch += 1; eventType = "DelegationRevoked"; } break;
      case "DisableUser": if (state.status !== "ACTIVE") throw new OnyxError("INVALID_STATE_TRANSITION", "user is not active"); state.status = "DISABLED"; state.lifecycleEpoch += 1; state.authorityEpoch += 1; eventType = "UserDisabled"; break;
      case "EnableUser": if (state.status !== "DISABLED") throw new OnyxError("INVALID_STATE_TRANSITION", "user is not disabled"); state.status = "ACTIVE"; state.lifecycleEpoch += 1; state.authorityEpoch += 1; eventType = "UserEnabled"; break;
    }
    state.version += 1; return this.#publish(command, state, eventType, structuredClone(command.payload), false);
  }
  async #create(command: Extract<IdentityCommand, {command_type: "CreateUser"}>) { if (await this.repository.find(command.payload.user_id)) throw new OnyxError("VERSION_CONFLICT", "user exists"); if (command.expected_version !== undefined && command.expected_version !== 0) throw new OnyxError("VERSION_CONFLICT", "new user must expect version 0"); const state: UserIdentity = {userId: command.payload.user_id, organizationId: command.organization_id, email: command.payload.email.toLowerCase(), displayName: command.payload.display_name, status: "ACTIVE", version: 1, lifecycleEpoch: 0, authorityEpoch: command.authority_proof.authority_epoch, roles: {}, devices: {}, delegations: {}}; return this.#publish(command, state, "UserCreated", {...command.payload, email: state.email}, true); }
  async #load(command: Exclude<IdentityCommand, {command_type: "CreateUser"}>) { const state = await this.repository.find(command.payload.user_id); if (!state) throw new OnyxError("NOT_FOUND", "user not found"); if (state.organizationId !== command.organization_id) throw new OnyxError("ORGANIZATION_MISMATCH", "user belongs to another organization"); if (command.command_type !== "EnableUser" && state.status === "DISABLED") throw new OnyxError("INVALID_STATE_TRANSITION", "user is disabled"); if (command.expected_version !== undefined && command.expected_version !== state.version) throw new OnyxError("VERSION_CONFLICT", "expected_version does not match"); if (command.expected_lifecycle_epoch !== undefined && command.expected_lifecycle_epoch !== state.lifecycleEpoch) throw new OnyxError("LIFECYCLE_EPOCH_MISMATCH", "expected_lifecycle_epoch does not match"); if (command.authority_proof.authority_epoch !== state.authorityEpoch || (command.expected_authority_epoch !== undefined && command.expected_authority_epoch !== state.authorityEpoch)) throw new OnyxError("AUTHORITY_EPOCH_MISMATCH", "authority epoch does not match"); return state; }
  #authorize(command: IdentityCommand) { const required = scopes[command.command_type]; if (!command.authority_proof.scope.includes(required) || Date.parse(command.authority_proof.expires_at) <= this.#now().getTime()) throw new OnyxError("AUTHORITY_PROOF_INVALID", `${required} authority is missing or expired`); }
  async #replay(command: IdentityCommand) { const prior = await this.repository.findOperation(command.operation_id); if (!prior) return undefined; if (prior.fingerprint !== sha256(command)) throw new OnyxError("IDEMPOTENCY_KEY_REUSE", "operation_id reused"); return prior.event; }
  async #publish(command: IdentityCommand, state: UserIdentity, eventType: IdentityEvent["event_type"], payload: unknown, create: boolean) { const now = this.#now(), occurredAt = utcInstant(now); const unsigned = {event_id: uuidV7(now), event_type: eventType, schema_version: 1 as const, organization_id: state.organizationId, aggregate: {aggregate_type: "User", object_id: state.userId}, aggregate_version: state.version, lifecycle_epoch: state.lifecycleEpoch, authority_epoch: state.authorityEpoch, operation_id: command.operation_id, actor_context: command.actor_context, occurred_at: occurredAt, recorded_at: occurredAt, vector_clock: this.#advance(command.vector_clock), correlation_id: command.correlation_id, causation_id: command.command_id, payload}; const event = {...unsigned, audit: {provenance: `${command.command_type}@1`, integrity_digest: sha256(unsigned)}} as IdentityEvent; assertEmittedEvent(event, eventType, "User"); await this.repository.commit(state, event, command.operation_id, {fingerprint: sha256(command), event}, create); return structuredClone(event); }
  #advance(clock: VectorClock): VectorClock { return {...clock, [this.#replicaId]: (clock[this.#replicaId] ?? 0) + 1}; }
  async getUser(organizationId: string, userId: string): Promise<UserIdentityView> { const state = await this.repository.find(userId); if (!state) throw new OnyxError("NOT_FOUND", "user not found"); if (state.organizationId !== organizationId) throw new OnyxError("ORGANIZATION_MISMATCH", "user belongs to another organization"); return toUserIdentityView(state); }
  async listUsers(organizationId: string, afterId?: string, limit = 100) { return (await this.repository.list(organizationId, afterId, limit)).map(toUserIdentityView); }
  async getHistory(organizationId: string, userId: string, afterVersion = 0, limit = 100) { if (!Number.isInteger(afterVersion) || afterVersion < 0 || !Number.isInteger(limit) || limit < 1 || limit > 1000) throw new OnyxError("INVALID_ARGUMENT", "invalid history pagination"); await this.getUser(organizationId, userId); return this.repository.history(userId, afterVersion, limit); }
}
