import type { ContextLink, ContextLinkEvent, ContextLinkView } from "./types.ts";
export interface ContextLinkOperationRecord { fingerprint: string; event: ContextLinkEvent }
export interface ContextLinkRepository { find(id: string): Promise<ContextLink | undefined>; list(organizationId: string, afterId: string | undefined, limit: number): Promise<ContextLink[]>; history(id: string, afterVersion?: number, limit?: number): Promise<ContextLinkEvent[]>; findOperation(id: string): Promise<ContextLinkOperationRecord | undefined>; commit(state: ContextLink, event: ContextLinkEvent, operationId: string, record: ContextLinkOperationRecord, create: boolean): Promise<void> }
export class InMemoryContextLinkRepository implements ContextLinkRepository {
  readonly #states = new Map<string, ContextLink>(); readonly #events = new Map<string, ContextLinkEvent[]>(); readonly #operations = new Map<string, ContextLinkOperationRecord>();
  async find(id: string) { const value = this.#states.get(id); return value && structuredClone(value); }
  async list(organizationId: string, afterId: string | undefined, limit: number) { return [...this.#states.values()].filter((value) => value.organizationId === organizationId && (afterId === undefined || value.contextLinkId > afterId)).sort((a,b) => a.contextLinkId.localeCompare(b.contextLinkId)).slice(0,limit).map((value) => structuredClone(value)); }
  async history(id: string, afterVersion=0, limit=100) { return (this.#events.get(id) ?? []).filter((event) => event.aggregate_version > afterVersion).slice(0,limit).map((event) => structuredClone(event)); }
  async findOperation(id: string) { const value=this.#operations.get(id); return value && structuredClone(value); }
  async commit(state: ContextLink, event: ContextLinkEvent, operationId: string, record: ContextLinkOperationRecord, create: boolean) { if (create === this.#states.has(state.contextLinkId)) throw new Error(create ? "context link exists" : "context link not found"); if (this.#operations.has(operationId)) throw new Error("operation exists"); this.#states.set(state.contextLinkId,structuredClone(state)); this.#events.set(state.contextLinkId,[...(this.#events.get(state.contextLinkId) ?? []),structuredClone(event)]); this.#operations.set(operationId,structuredClone(record)); }
}
export function toContextLinkView(state: ContextLink): ContextLinkView { return {context_link_id:state.contextLinkId,organization_id:state.organizationId,source_ref:structuredClone(state.sourceRef),target_ref:structuredClone(state.targetRef),relation_type:state.relationType,strength:state.strength,metadata:{...state.metadata},status:state.status,version:state.version,lifecycle_epoch:state.lifecycleEpoch,authority_epoch:state.authorityEpoch}; }
