import type { DomainObjectRef, VectorClock } from "../contracts/envelopes.ts";
import { OnyxError } from "../contracts/errors.ts";
import { assertEmittedEvent } from "../contracts/validation.ts";
import { sha256 } from "../shared/canonical-json.ts";
import { utcInstant, uuidV7 } from "../shared/identifiers.ts";
import { toContextLinkView, type ContextLinkRepository } from "./repository.ts";
import type { ContextLink, ContextLinkCommand, ContextLinkEvent, ContextLinkView } from "./types.ts";
import { validateContextLinkCommand } from "./validation.ts";
export interface ContextLinkServiceOptions {repository:ContextLinkRepository;requireObject:(organizationId:string,reference:DomainObjectRef)=>Promise<void>;now?:()=>Date;replicaId?:string}
const scopes:Record<ContextLinkCommand["command_type"],string>={CreateContextLink:"context:create",UpdateContextMetadata:"context:metadata:update",ChangeContextStrength:"context:strength:change",ArchiveContextLink:"context:archive",RestoreContextLink:"context:restore"};
export class ContextLinkService {readonly #repository:ContextLinkRepository;readonly #requireObject:ContextLinkServiceOptions["requireObject"];readonly #now:()=>Date;readonly #replicaId:string;
  constructor(options:ContextLinkServiceOptions){this.#repository=options.repository;this.#requireObject=options.requireObject;this.#now=options.now??(()=>new Date());this.#replicaId=options.replicaId??"context-service";}
  async execute(input:unknown):Promise<ContextLinkEvent>{validateContextLinkCommand(input);const command=input;this.#authorize(command);const replay=await this.#replay(command);if(replay)return replay;if(command.command_type==="CreateContextLink")return this.#create(command);const state=await this.#load(command);let eventType:ContextLinkEvent["event_type"];
    switch(command.command_type){case "UpdateContextMetadata":if(state.status!=="ACTIVE")throw new OnyxError("INVALID_STATE_TRANSITION","archived context link is immutable");state.metadata={...command.payload.metadata};eventType="ContextMetadataUpdated";break;case "ChangeContextStrength":if(state.status!=="ACTIVE")throw new OnyxError("INVALID_STATE_TRANSITION","archived context link is immutable");if(state.strength===command.payload.strength)throw new OnyxError("INVALID_STATE_TRANSITION","context strength is unchanged");state.strength=command.payload.strength;eventType="ContextStrengthChanged";break;case "ArchiveContextLink":if(state.status!=="ACTIVE")throw new OnyxError("INVALID_STATE_TRANSITION","context link is already archived");state.status="ARCHIVED";state.lifecycleEpoch+=1;eventType="ContextLinkArchived";break;case "RestoreContextLink":if(state.status!=="ARCHIVED")throw new OnyxError("INVALID_STATE_TRANSITION","context link is not archived");await this.#requireObject(state.organizationId,state.sourceRef);await this.#requireObject(state.organizationId,state.targetRef);state.status="ACTIVE";state.lifecycleEpoch+=1;eventType="ContextLinkRestored";break;}
    state.version+=1;return this.#publish(command,state,eventType,structuredClone(command.payload),false);}
  async #create(command:Extract<ContextLinkCommand,{command_type:"CreateContextLink"}>){if(command.expected_version!==undefined&&command.expected_version!==0)throw new OnyxError("VERSION_CONFLICT","new context link must expect version 0");if(await this.#repository.find(command.payload.context_link_id))throw new OnyxError("VERSION_CONFLICT","context link exists");await this.#requireObject(command.organization_id,command.payload.source_ref);await this.#requireObject(command.organization_id,command.payload.target_ref);const state:ContextLink={contextLinkId:command.payload.context_link_id,organizationId:command.organization_id,sourceRef:structuredClone(command.payload.source_ref),targetRef:structuredClone(command.payload.target_ref),relationType:command.payload.relation_type,strength:command.payload.strength,metadata:{...command.payload.metadata},status:"ACTIVE",version:1,lifecycleEpoch:0,authorityEpoch:command.authority_proof.authority_epoch};return this.#publish(command,state,"ContextLinkCreated",structuredClone(command.payload),true);}
  async #load(command:Exclude<ContextLinkCommand,{command_type:"CreateContextLink"}>){const state=await this.#repository.find(command.payload.context_link_id);if(!state||state.organizationId!==command.organization_id)throw new OnyxError("NOT_FOUND","context link not found");if(command.expected_version!==undefined&&command.expected_version!==state.version)throw new OnyxError("VERSION_CONFLICT","expected_version does not match");if(command.expected_lifecycle_epoch!==undefined&&command.expected_lifecycle_epoch!==state.lifecycleEpoch)throw new OnyxError("LIFECYCLE_EPOCH_MISMATCH","expected_lifecycle_epoch does not match");if(command.expected_authority_epoch!==undefined&&command.expected_authority_epoch!==state.authorityEpoch)throw new OnyxError("AUTHORITY_EPOCH_MISMATCH","expected_authority_epoch does not match");return state;}
  #authorize(command:ContextLinkCommand){const scope=scopes[command.command_type];if(!command.authority_proof.scope.includes(scope)||Date.parse(command.authority_proof.expires_at)<=this.#now().getTime())throw new OnyxError("AUTHORITY_PROOF_INVALID",`${scope} authority is missing or expired`);}
  async #replay(command:ContextLinkCommand){const prior=await this.#repository.findOperation(command.operation_id);if(!prior)return undefined;if(prior.fingerprint!==sha256(command))throw new OnyxError("IDEMPOTENCY_KEY_REUSE","operation_id reused");return prior.event;}
  async #publish(command:ContextLinkCommand,state:ContextLink,eventType:ContextLinkEvent["event_type"],payload:unknown,create:boolean){const now=this.#now(),occurredAt=utcInstant(now);const unsigned={event_id:uuidV7(now),event_type:eventType,schema_version:1 as const,organization_id:state.organizationId,aggregate:{aggregate_type:"ContextLink",object_id:state.contextLinkId},aggregate_version:state.version,lifecycle_epoch:state.lifecycleEpoch,authority_epoch:state.authorityEpoch,operation_id:command.operation_id,actor_context:command.actor_context,occurred_at:occurredAt,recorded_at:occurredAt,vector_clock:this.#advance(command.vector_clock),correlation_id:command.correlation_id,causation_id:command.command_id,payload};const event={...unsigned,audit:{provenance:`${command.command_type}@1`,integrity_digest:sha256(unsigned)}} as ContextLinkEvent;assertEmittedEvent(event,eventType,"ContextLink");await this.#repository.commit(state,event,command.operation_id,{fingerprint:sha256(command),event},create);return structuredClone(event);}
  #advance(clock:VectorClock):VectorClock{return {...clock,[this.#replicaId]:(clock[this.#replicaId]??0)+1};}
  async getContextLink(organizationId:string,id:string):Promise<ContextLinkView>{const state=await this.#repository.find(id);if(!state||state.organizationId!==organizationId)throw new OnyxError("NOT_FOUND","context link not found");return toContextLinkView(state);}
  async listContextLinks(organizationId:string,afterId?:string,limit=100){return(await this.#repository.list(organizationId,afterId,limit)).map(toContextLinkView);}
  async getHistory(organizationId:string,id:string,afterVersion=0,limit=100){if(!Number.isInteger(afterVersion)||afterVersion<0||!Number.isInteger(limit)||limit<1||limit>1000)throw new OnyxError("INVALID_ARGUMENT","invalid history pagination");await this.getContextLink(organizationId,id);return this.#repository.history(id,afterVersion,limit);}
}
