import { exactKeys, fail, object, text, uuid, validateCommandEnvelope } from "../contracts/validation.ts";
import type { ContextLinkCommand, ContextStrength } from "./types.ts";
const types = new Set(["CreateContextLink","UpdateContextMetadata","ChangeContextStrength","ArchiveContextLink","RestoreContextLink"]), strengths = new Set<ContextStrength>(["WEAK","NORMAL","STRONG","CRITICAL"]);
function base(command:Record<string,any>, keys:string[]){const value=object(command.payload,"payload");exactKeys(value,keys,"payload");uuid(value.context_link_id,"payload.context_link_id");if(command.target.object_id!==value.context_link_id)fail("target object must match payload context_link_id");return value;}
function ref(value:unknown,path:string){const item=object(value,path);exactKeys(item,["aggregate_type","object_id"],path);text(item.aggregate_type,`${path}.aggregate_type`,120);uuid(item.object_id,`${path}.object_id`);return item;}
function metadata(value:unknown){const item=object(value,"payload.metadata"), entries=Object.entries(item);if(entries.length>50)fail("payload.metadata has too many entries");for(const [key,child] of entries){if(!/^[a-zA-Z0-9_.-]{1,100}$/.test(key))fail("payload.metadata key is invalid");text(child,`payload.metadata.${key}`,1000);}return item;}
export function validateContextLinkCommand(value:unknown): asserts value is ContextLinkCommand { const type=(value as {command_type?:string})?.command_type;if(typeof type!=="string"||!types.has(type))fail("command is not implemented");const command=validateCommandEnvelope(value,type,"ContextLink") as Record<string,any>;let data:Record<string,any>;
  switch(type){case "CreateContextLink":data=base(command,["context_link_id","source_ref","target_ref","relation_type","strength","metadata"]);{const source=ref(data.source_ref,"payload.source_ref"),target=ref(data.target_ref,"payload.target_ref");if(source.aggregate_type===target.aggregate_type&&source.object_id===target.object_id)fail("context link endpoints must differ");}text(data.relation_type,"payload.relation_type",120);if(!strengths.has(data.strength))fail("payload.strength is invalid");metadata(data.metadata);return;
    case "UpdateContextMetadata":data=base(command,["context_link_id","metadata"]);metadata(data.metadata);return;
    case "ChangeContextStrength":data=base(command,["context_link_id","strength","reason"]);if(!strengths.has(data.strength))fail("payload.strength is invalid");text(data.reason,"payload.reason",2000);return;
    case "ArchiveContextLink":case "RestoreContextLink":data=base(command,["context_link_id","reason"]);text(data.reason,"payload.reason",2000);return;}
}
