apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: onyx-ifem

resources:
  - namespace.yaml
  - service-account.yaml
  - configmap.yaml
  - services.yaml
  - statefulset.yaml
  - network-policy.yaml

images:
  - name: ghcr.io/lamatech-dev/onyx-ifem
    newName: ghcr.io/lamatech-dev/onyx-ifem
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
